apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netflix.fullname" . }}-secret
type: Opaque
stringData:
  IMAP_USER: {{ .Values.secret.imapUser | quote }}
  IMAP_PASSWORD: {{ .Values.secret.imapPassword | quote }}